services:
  api:
    build:
      context: .
    container_name: fastapi-hvv
    env_file:
      - .env
    environment:
      PORT: 7555
    ports:
      - '80:7555'
    restart: "no"
    volumes:
      - ./app:/code
      - ./my_database.db:/code/my_database.db
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port 7555 --reload
