name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Code Checkout
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container
        run: |
          docker compose up -d  # Start the FastAPI app in Docker

      - name: Wait for FastAPI to be ready
        run: |
          timeout 60 sh -c 'until curl -sSf http://localhost/docs; do sleep 2; done'

      - name: Run tests
        run: |
          docker exec fastapi-hvv pytest  # Run tests inside the Docker container

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image using Docker Compose
      run: docker compose -f compose.yaml build api  

    - name: Tag the Docker image
      run: docker tag docker.io/library/hvv-pitch-backend-data-api ghcr.io/${{ github.repository }}/fastapi-hvv:latest

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/fastapi-hvv:latest
