name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # Trigger the workflow when a push is made to the dev branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Code Checkout
      - name: Check out code
        uses: actions/checkout@v2

      # Python Setup
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Tests
      - name: Run Tests
        run: pytest

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build the Docker images using docker compose
    - name: Build Docker Compose services
      run: docker compose -f docker-compose.yaml build

    # Push the Docker images to GitHub Container Registry
    - name: Push Docker images to GitHub Container Registry
      run: docker compose -f docker-compose.yaml push